version: "3.9"

services:
  # --- BACKEND (NestJS) ---
  backend:
    build: ./backend
    container_name: nest_backend
    env_file: .env
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      - db
    networks:
      - app_network
    command: npm run start:dev
    volumes:
      - ./backend:/app
      - /app/node_modules

  # --- FRONTEND (Vite) ---
  frontend:
    build: ./frontend
    container_name: vite_frontend
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:5173"
    networks:
      - app_network
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  # --- NGINX (Proxy / Servidor) ---
  nginx:
    build: ./nginx
    container_name: nginx_server
    env_file: .env
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  # --- MYSQL ---
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - app_network

  # --- PHPMYADMIN ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    env_file: .env
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db
    networks:
      - app_network

# --- VOLUMES ---
volumes:
  db_data:

# --- NETWORK ---
networks:
  app_network:
    driver: bridge
